"use client";

import { useState, useRef, useEffect, useCallback } from "react";

interface VideoInfo {
  title: string;
  author: string;
  thumbnail: string;
}

interface AnalyzeResult {
  videoInfo: VideoInfo;
  transcript: {
    text: string;
    language: string;
    autoGenerated: boolean;
    charCount: number;
  };
  summary: string;
  mode: string;
}

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

const YT_PATTERNS = [
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?v=([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?youtu\.be\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/,
];

function extractVideoId(url: string): string | null {
  for (const pattern of YT_PATTERNS) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function Markdown({ text }: { text: string }) {
  // Simple markdown rendering
  const html = text
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold mt-5 mb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mt-6 mb-3">$1</h1>')
    .replace(/^- (.+)$/gm, '<li class="ml-4 list-disc">$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li class="ml-4 list-decimal">$2</li>')
    .replace(/`([^`]+)`/g, '<code class="bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded text-sm">$1</code>')
    .replace(/\n\n/g, '</p><p class="mb-3">')
    .replace(/\n/g, "<br />");
  return (
    <div
      className="prose dark:prose-invert max-w-none leading-relaxed"
      dangerouslySetInnerHTML={{ __html: `<p class="mb-3">${html}</p>` }}
    />
  );
}

export default function YouTubePage() {
  const [url, setUrl] = useState("");
  const [mode, setMode] = useState<"summary" | "full" | "key_points">("summary");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<AnalyzeResult | null>(null);

  // Chat state
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const [showManualInput, setShowManualInput] = useState(false);
  const [manualTranscript, setManualTranscript] = useState("");
  const [manualLoading, setManualLoading] = useState(false);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  const handleAnalyze = useCallback(async () => {
    const videoId = extractVideoId(url.trim());
    if (!videoId) {
      setError("유효한 YouTube URL을 입력해주세요.");
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);
    setChatMessages([]);

    try {
      const resp = await fetch("/api/youtube/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ videoId, mode }),
      });

      const data = await resp.json();

      if (!resp.ok) {
        if (data.videoInfo) {
          setResult({
            videoInfo: data.videoInfo,
            transcript: { text: "", language: "", autoGenerated: false, charCount: 0 },
            summary: "",
            mode,
          });
        }
        // 자막이 있지만 서버에서 다운로드 실패 시 수동 입력 안내
        if (data.hasSubtitles) {
          setError("자막 자동 추출이 차단되었습니다. 아래에서 자막을 직접 붙여넣어 주세요.");
        } else {
          setError(data.error || "분석에 실패했습니다.");
        }
        setShowManualInput(true);
        return;
      }

      setResult(data);
    } catch {
      setError("서버에 연결할 수 없습니다.");
    } finally {
      setLoading(false);
    }
  }, [url, mode]);

  const handleChat = useCallback(async () => {
    if (!chatInput.trim() || !result?.transcript.text) return;

    const question = chatInput.trim();
    setChatInput("");
    setChatMessages((prev) => [...prev, { role: "user", content: question }]);
    setChatLoading(true);

    try {
      const resp = await fetch("/api/youtube/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          question,
          transcript: result.transcript.text,
          videoTitle: result.videoInfo.title,
        }),
      });

      const data = await resp.json();
      if (resp.ok) {
        setChatMessages((prev) => [...prev, { role: "assistant", content: data.answer }]);
      } else {
        setChatMessages((prev) => [...prev, { role: "assistant", content: `오류: ${data.error}` }]);
      }
    } catch {
      setChatMessages((prev) => [...prev, { role: "assistant", content: "서버 연결 오류" }]);
    } finally {
      setChatLoading(false);
    }
  }, [chatInput, result]);

  const handleManualAnalyze = useCallback(async () => {
    if (!manualTranscript.trim()) return;

    setManualLoading(true);
    setError("");

    try {
      const videoId = extractVideoId(url.trim());
      const resp = await fetch("/api/youtube/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          videoId: videoId || "manual00000",
          mode,
          manualTranscript: manualTranscript.trim(),
        }),
      });

      const data = await resp.json();
      if (resp.ok) {
        setResult(data);
        setShowManualInput(false);
      } else {
        setError(data.error || "분석에 실패했습니다.");
      }
    } catch {
      setError("서버에 연결할 수 없습니다.");
    } finally {
      setManualLoading(false);
    }
  }, [manualTranscript, url, mode]);

  const modeLabels = {
    summary: "요약",
    full: "전체 정리",
    key_points: "핵심 포인트",
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-950 dark:to-gray-900">
      {/* Header */}
      <header className="border-b border-gray-200 dark:border-gray-800 bg-white/80 dark:bg-gray-950/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-3">
          <div className="w-10 h-10 bg-red-600 rounded-xl flex items-center justify-center text-white font-bold text-lg">
            Y
          </div>
          <div>
            <h1 className="text-xl font-bold text-gray-900 dark:text-white">YouTube 분석</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              영상 자막 추출 + AI 분석 + 질문 답변
            </p>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8 space-y-6">
        {/* Input Section */}
        <section className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 p-6">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                YouTube URL
              </label>
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !loading) handleAnalyze();
                }}
                placeholder="https://www.youtube.com/watch?v=..."
                className="w-full px-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent transition"
              />
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <div className="flex gap-2">
                {(Object.entries(modeLabels) as [keyof typeof modeLabels, string][]).map(
                  ([key, label]) => (
                    <button
                      key={key}
                      onClick={() => setMode(key)}
                      className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
                        mode === key
                          ? "bg-red-600 text-white shadow-sm"
                          : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
                      }`}
                    >
                      {label}
                    </button>
                  )
                )}
              </div>

              <button
                onClick={handleAnalyze}
                disabled={loading || !url.trim()}
                className="ml-auto px-6 py-2.5 bg-red-600 hover:bg-red-700 disabled:bg-gray-400 text-white rounded-xl font-medium transition shadow-sm disabled:shadow-none"
              >
                {loading ? (
                  <span className="flex items-center gap-2">
                    <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    분석 중...
                  </span>
                ) : (
                  "분석하기"
                )}
              </button>
            </div>
          </div>
        </section>

        {/* Error */}
        {error && (
          <div className="bg-red-50 dark:bg-red-950/50 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-xl">
            {error}
          </div>
        )}

        {/* Manual Transcript Input */}
        {showManualInput && (
          <section className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 p-6">
            <h3 className="font-semibold text-gray-900 dark:text-white mb-2">
              자막 직접 입력
            </h3>
            <div className="text-sm text-gray-500 dark:text-gray-400 mb-3 space-y-1">
              <p>YouTube에서 자막을 복사해서 붙여넣으세요.</p>
              <ol className="list-decimal ml-5 space-y-0.5">
                <li>YouTube 영상 페이지에서 영상 아래 <strong>...더보기</strong> 클릭</li>
                <li><strong>스크립트 보기</strong> 클릭</li>
                <li>텍스트를 전체 선택(Ctrl+A)하고 복사(Ctrl+C)</li>
                <li>아래 입력란에 붙여넣기(Ctrl+V)</li>
              </ol>
            </div>
            <textarea
              value={manualTranscript}
              onChange={(e) => setManualTranscript(e.target.value)}
              placeholder="자막 텍스트를 여기에 붙여넣으세요..."
              rows={8}
              className="w-full px-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent transition text-sm resize-y"
            />
            <div className="flex items-center justify-between mt-3">
              <span className="text-xs text-gray-400">
                {manualTranscript.length > 0 ? `${manualTranscript.length.toLocaleString()}자` : ""}
              </span>
              <div className="flex gap-2">
                <button
                  onClick={() => setShowManualInput(false)}
                  className="px-4 py-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition"
                >
                  닫기
                </button>
                <button
                  onClick={handleManualAnalyze}
                  disabled={manualLoading || !manualTranscript.trim()}
                  className="px-5 py-2 bg-red-600 hover:bg-red-700 disabled:bg-gray-400 text-white rounded-xl font-medium transition text-sm"
                >
                  {manualLoading ? "분석 중..." : "분석하기"}
                </button>
              </div>
            </div>
          </section>
        )}

        {/* Result */}
        {result && (
          <>
            {/* Video Info */}
            <section className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 overflow-hidden">
              <div className="flex flex-col sm:flex-row">
                {result.videoInfo.thumbnail && (
                  <div className="sm:w-72 flex-shrink-0">
                    <img
                      src={result.videoInfo.thumbnail}
                      alt={result.videoInfo.title}
                      className="w-full h-full object-cover"
                    />
                  </div>
                )}
                <div className="p-5 flex flex-col justify-center">
                  <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-1">
                    {result.videoInfo.title || "제목 없음"}
                  </h2>
                  {result.videoInfo.author && (
                    <p className="text-sm text-gray-500 dark:text-gray-400 mb-3">
                      {result.videoInfo.author}
                    </p>
                  )}
                  {result.transcript.charCount > 0 && (
                    <div className="flex flex-wrap gap-2 text-xs">
                      <span className="px-2 py-1 bg-gray-100 dark:bg-gray-800 rounded-md text-gray-600 dark:text-gray-400">
                        자막: {result.transcript.language}
                        {result.transcript.autoGenerated && " (자동 생성)"}
                      </span>
                      <span className="px-2 py-1 bg-gray-100 dark:bg-gray-800 rounded-md text-gray-600 dark:text-gray-400">
                        {result.transcript.charCount.toLocaleString()}자
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </section>

            {/* Summary */}
            {result.summary && (
              <section className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 p-6">
                <h3 className="text-sm font-semibold text-red-600 dark:text-red-400 uppercase tracking-wider mb-4">
                  {modeLabels[result.mode as keyof typeof modeLabels] || "요약"}
                </h3>
                <Markdown text={result.summary} />
              </section>
            )}

            {/* Chat Section */}
            {result.transcript.text && (
              <section className="bg-white dark:bg-gray-900 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-800 overflow-hidden">
                <div className="p-4 border-b border-gray-200 dark:border-gray-800">
                  <h3 className="font-semibold text-gray-900 dark:text-white">
                    영상에 대해 질문하기
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    영상 내용을 바탕으로 궁금한 점을 물어보세요
                  </p>
                </div>

                {/* Chat Messages */}
                {chatMessages.length > 0 && (
                  <div className="p-4 space-y-4 max-h-[500px] overflow-y-auto">
                    {chatMessages.map((msg, i) => (
                      <div
                        key={i}
                        className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                      >
                        <div
                          className={`max-w-[85%] rounded-2xl px-4 py-3 ${
                            msg.role === "user"
                              ? "bg-red-600 text-white"
                              : "bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white"
                          }`}
                        >
                          {msg.role === "assistant" ? (
                            <Markdown text={msg.content} />
                          ) : (
                            <p className="text-sm">{msg.content}</p>
                          )}
                        </div>
                      </div>
                    ))}
                    {chatLoading && (
                      <div className="flex justify-start">
                        <div className="bg-gray-100 dark:bg-gray-800 rounded-2xl px-4 py-3">
                          <div className="flex gap-1.5">
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" />
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce [animation-delay:0.15s]" />
                            <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce [animation-delay:0.3s]" />
                          </div>
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>
                )}

                {/* Chat Input */}
                <div className="p-4 border-t border-gray-200 dark:border-gray-800">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && !chatLoading) handleChat();
                      }}
                      placeholder="이 영상에서 가장 중요한 주장은 뭐야?"
                      className="flex-1 px-4 py-2.5 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent transition text-sm"
                      disabled={chatLoading}
                    />
                    <button
                      onClick={handleChat}
                      disabled={chatLoading || !chatInput.trim()}
                      className="px-4 py-2.5 bg-red-600 hover:bg-red-700 disabled:bg-gray-400 text-white rounded-xl font-medium transition text-sm"
                    >
                      전송
                    </button>
                  </div>
                </div>
              </section>
            )}
          </>
        )}

        {/* Empty State */}
        {!result && !loading && !error && (
          <section className="text-center py-12 text-gray-400 dark:text-gray-600">
            <div className="text-6xl mb-4">
              <svg className="mx-auto w-16 h-16" fill="currentColor" viewBox="0 0 24 24">
                <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0C.488 3.45.029 5.804 0 12c.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0C23.512 20.55 23.971 18.196 24 12c-.029-6.185-.484-8.549-4.385-8.816zM9 16V8l8 4-8 4z"/>
              </svg>
            </div>
            <p className="text-lg font-medium mb-1">YouTube URL을 입력하세요</p>
            <p className="text-sm mb-8">영상의 자막을 추출하고 AI가 분석합니다</p>

            <div className="max-w-lg mx-auto">
              <p className="text-xs uppercase tracking-wider text-gray-400 dark:text-gray-600 mb-3">샘플 영상으로 테스트</p>
              <div className="grid gap-2">
                {[
                  { id: "dQw4w9WgXcQ", title: "Rick Astley - Never Gonna Give You Up", channel: "Rick Astley" },
                  { id: "Ks-_Mh1QhMc", title: "The Future of AI (TED)", channel: "TED" },
                  { id: "aircAruvnKk", title: "How to Learn Anything Fast", channel: "Ali Abdaal" },
                ].map((sample) => (
                  <button
                    key={sample.id}
                    onClick={() => {
                      setUrl(`https://www.youtube.com/watch?v=${sample.id}`);
                    }}
                    className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 hover:border-red-300 dark:hover:border-red-700 hover:shadow-sm transition text-left group"
                  >
                    <img
                      src={`https://img.youtube.com/vi/${sample.id}/mqdefault.jpg`}
                      alt={sample.title}
                      className="w-20 h-12 object-cover rounded-lg flex-shrink-0"
                    />
                    <div className="min-w-0">
                      <p className="text-sm font-medium text-gray-700 dark:text-gray-300 group-hover:text-red-600 dark:group-hover:text-red-400 truncate transition">
                        {sample.title}
                      </p>
                      <p className="text-xs text-gray-400 dark:text-gray-600">{sample.channel}</p>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </section>
        )}
      </main>
    </div>
  );
}
