import { NextResponse } from "next/server";
import { getSecret } from "@/lib/secrets";
import Anthropic from "@anthropic-ai/sdk";
import { Innertube } from "youtubei.js";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

const BROWSER_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

function parseXmlTranscript(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const entryRegex = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match;
  while ((match = entryRegex.exec(xml)) !== null) {
    const text = match[3]
      .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/<[^>]+>/g, "").trim();
    if (text) {
      segments.push({ start: parseFloat(match[1]), duration: parseFloat(match[2]), text });
    }
  }
  return segments;
}

async function fetchTranscript(videoId: string): Promise<{
  ok: boolean;
  text?: string;
  segments?: TranscriptSegment[];
  language?: string;
  autoGenerated?: boolean;
  error?: string;
  hasSubtitles?: boolean;
}> {
  // Method 1: youtubei.js (Innertube API 래퍼)
  try {
    const yt = await Innertube.create();
    const info = await yt.getInfo(videoId);
    const transcript = await info.getTranscript();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const body = (transcript as any)?.transcript?.content?.body;
    const segList = body?.initialSegments || [];
    if (segList.length > 0) {
      const segments: TranscriptSegment[] = [];
      for (const seg of segList) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const renderer = (seg as any)?.transcriptSegmentRenderer;
        if (renderer) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const text = renderer.snippet?.runs?.map((r: any) => r.text || "").join("").trim() || "";
          const startMs = parseInt(renderer.startMs || "0", 10);
          const endMs = parseInt(renderer.endMs || "0", 10);
          if (text) segments.push({ start: startMs / 1000, duration: (endMs - startMs) / 1000, text });
        }
      }
      if (segments.length > 0) {
        return { ok: true, text: segments.map(s => s.text).join(" "), segments, language: "auto", autoGenerated: false };
      }
    }
  } catch (e) {
    console.error("youtubei.js error:", e instanceof Error ? e.message : e);
  }

  // Method 2: HTML 스크래핑 + 캡션 URL 다운로드
  try {
    const cookies = "SOCS=CAISNQgDEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMxMTE0LjA3X3AxGgJlbiACGgYIgJnsBxQB; CONSENT=YES+cb.20210328-17-p0.en+FX+987";
    const pageResp = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: { "Accept-Language": "ko,en;q=0.9", "User-Agent": BROWSER_UA, "Cookie": cookies },
      cache: "no-store",
    });
    const html = await pageResp.text();

    // playerResponse에서 캡션 트랙 추출
    let startIdx = html.indexOf("var ytInitialPlayerResponse");
    if (startIdx === -1) startIdx = html.indexOf("ytInitialPlayerResponse");
    if (startIdx !== -1) {
      const braceStart = html.indexOf("{", startIdx);
      let depth = 0, jsonEnd = braceStart;
      for (let i = braceStart; i < html.length; i++) {
        if (html[i] === "{") depth++;
        else if (html[i] === "}") { depth--; if (depth === 0) { jsonEnd = i + 1; break; } }
      }
      const playerData = JSON.parse(html.slice(braceStart, jsonEnd));
      const tracks = playerData?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

      if (tracks.length === 0) {
        return { ok: false, error: "이 영상에는 자막이 없습니다.", hasSubtitles: false };
      }

      // 선호 언어 순으로 트랙 선택
      const preferred = ["ko", "en", "ja"];
      let track = tracks[0];
      for (const lang of preferred) {
        const found = tracks.find((t: { languageCode: string }) => t.languageCode === lang);
        if (found) { track = found; break; }
      }

      // 캡션 URL 다운로드 시도
      const fetchHeaders = {
        "User-Agent": BROWSER_UA,
        "Cookie": cookies,
        "Referer": `https://www.youtube.com/watch?v=${videoId}`,
      };

      const xmlResp = await fetch(track.baseUrl, { headers: fetchHeaders, cache: "no-store" });
      if (xmlResp.ok) {
        const xml = await xmlResp.text();
        if (xml.length > 0) {
          const segments = parseXmlTranscript(xml);
          if (segments.length > 0) {
            return {
              ok: true, text: segments.map(s => s.text).join(" "), segments,
              language: track.languageCode, autoGenerated: track.kind === "asr",
            };
          }
        }
      }

      // 자막 트랙은 있지만 다운로드 실패
      return {
        ok: false,
        error: "자막이 있지만 서버에서 다운로드할 수 없습니다. 아래에서 자막을 직접 붙여넣어 주세요.",
        hasSubtitles: true,
      };
    }
  } catch (e) {
    console.error("HTML scraping error:", e instanceof Error ? e.message : e);
  }

  return { ok: false, error: "영상 데이터를 가져올 수 없습니다." };
}

async function fetchVideoInfo(videoId: string): Promise<{ title: string; author: string; thumbnail: string }> {
  try {
    const resp = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
      { cache: "no-store" }
    );
    if (resp.ok) {
      const data = await resp.json();
      return { title: data.title || "", author: data.author_name || "", thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` };
    }
  } catch { /* ignore */ }
  return { title: "", author: "", thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` };
}

export async function POST(request: Request) {
  try {
    const { videoId, mode = "summary", manualTranscript } = await request.json();

    if (!videoId || typeof videoId !== "string" || !/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
      return NextResponse.json({ error: "유효하지 않은 영상 ID입니다." }, { status: 400 });
    }

    const apiKey = await getSecret("ANTHROPIC_API_KEY");
    if (!apiKey) {
      return NextResponse.json({ error: "API 키가 설정되지 않았습니다." }, { status: 500 });
    }

    let videoInfo: { title: string; author: string; thumbnail: string };
    let transcriptText: string;
    let transcriptLanguage = "";
    let transcriptAutoGenerated = false;

    if (manualTranscript && typeof manualTranscript === "string" && manualTranscript.trim().length > 0) {
      videoInfo = await fetchVideoInfo(videoId);
      transcriptText = manualTranscript.trim();
    } else {
      const [vi, transcriptResult] = await Promise.all([
        fetchVideoInfo(videoId),
        fetchTranscript(videoId),
      ]);
      videoInfo = vi;

      if (!transcriptResult.ok) {
        return NextResponse.json({
          error: transcriptResult.error,
          videoInfo,
          hasSubtitles: transcriptResult.hasSubtitles,
        }, { status: 422 });
      }

      transcriptText = transcriptResult.text!;
      transcriptLanguage = transcriptResult.language || "";
      transcriptAutoGenerated = transcriptResult.autoGenerated || false;
    }

    const maxChars = 300_000;
    const truncated = transcriptText.length > maxChars
      ? transcriptText.slice(0, maxChars) + "\n\n... (자막이 너무 길어 일부만 포함)"
      : transcriptText;

    const titleHint = videoInfo.title ? `\n영상 제목: ${videoInfo.title}` : "";

    const prompts: Record<string, string> = {
      summary: `다음은 YouTube 영상의 자막입니다.${titleHint}\n\n이 영상의 내용을 한국어로 요약해주세요.\n\n요약 형식:\n1. **핵심 주제** (1-2줄)\n2. **주요 내용** (핵심 포인트 3-7개, 불릿)\n3. **결론/시사점** (1-2줄)\n\n자막:\n${truncated}`,
      full: `다음은 YouTube 영상의 자막입니다.${titleHint}\n\n이 자막을 깔끔하게 정리해주세요:\n- 말의 반복, 군더더기를 제거\n- 주제별로 구분\n- 읽기 쉽게 문단 나누기\n- 한국어로 작성 (원문이 영어면 번역)\n\n자막:\n${truncated}`,
      key_points: `다음은 YouTube 영상의 자막입니다.${titleHint}\n\n핵심 포인트만 추출해주세요:\n- 가장 중요한 인사이트 5-10개\n- 각 포인트는 1-2줄로 간결하게\n- 실행 가능한 조언이 있다면 별도 표시\n\n자막:\n${truncated}`,
    };

    const client = new Anthropic({ apiKey });
    const response = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 4000,
      system: "당신은 영상 내용을 정확하고 깊이있게 요약하는 전문가입니다. 마크다운 포맷으로 작성하세요.",
      messages: [{ role: "user", content: prompts[mode] || prompts.summary }],
    });

    const summary = response.content[0].type === "text" ? response.content[0].text : "";

    return NextResponse.json({
      videoInfo,
      transcript: { text: transcriptText, language: transcriptLanguage, autoGenerated: transcriptAutoGenerated, charCount: transcriptText.length },
      summary,
      mode,
    });
  } catch (error) {
    console.error("YouTube analyze error:", error);
    return NextResponse.json({ error: "분석 중 오류가 발생했습니다." }, { status: 500 });
  }
}
