import { NextResponse } from "next/server";
import { getSecret } from "@/lib/secrets";
import Anthropic from "@anthropic-ai/sdk";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

async function fetchTranscript(videoId: string): Promise<{
  ok: boolean;
  text?: string;
  segments?: TranscriptSegment[];
  language?: string;
  autoGenerated?: boolean;
  error?: string;
}> {
  // Use a public transcript proxy (innertube API)
  const languages = ["ko", "en", "ja"];

  for (const lang of languages) {
    try {
      // Try fetching via YouTube's timedtext API
      const url = `https://www.youtube.com/watch?v=${videoId}`;
      const pageResp = await fetch(url, {
        headers: { "Accept-Language": "ko,en;q=0.9" },
      });
      const html = await pageResp.text();

      // Extract captions data from page
      const captionsMatch = html.match(/"captions":\s*(\{[\s\S]*?"playerCaptionsTracklistRenderer"[\s\S]*?\})\s*,\s*"/);
      if (!captionsMatch) {
        continue;
      }

      // Find caption tracks
      const captionsJson = captionsMatch[1].replace(/\\n/g, "").replace(/\\"/g, '"');
      const trackMatches = [...captionsJson.matchAll(/"baseUrl"\s*:\s*"(https:\/\/www\.youtube\.com\/api\/timedtext[^"]+)"/g)];
      const langMatches = [...captionsJson.matchAll(/"languageCode"\s*:\s*"([^"]+)"/g)];

      if (trackMatches.length === 0) continue;

      // Find preferred language track
      let trackUrl = "";
      let selectedLang = "";
      let autoGenerated = false;

      for (const preferredLang of languages) {
        for (let i = 0; i < langMatches.length && i < trackMatches.length; i++) {
          if (langMatches[i][1] === preferredLang) {
            trackUrl = trackMatches[i][1].replace(/\\u0026/g, "&");
            selectedLang = preferredLang;
            autoGenerated = captionsJson.includes(`"kind":"asr"`) && i === 0;
            break;
          }
        }
        if (trackUrl) break;
      }

      // Fallback to first track
      if (!trackUrl && trackMatches.length > 0) {
        trackUrl = trackMatches[0][1].replace(/\\u0026/g, "&");
        selectedLang = langMatches[0]?.[1] || "unknown";
      }

      if (!trackUrl) continue;

      // Fetch the transcript XML
      const trackResp = await fetch(trackUrl);
      const xml = await trackResp.text();

      // Parse XML transcript
      const segments: TranscriptSegment[] = [];
      const textParts: string[] = [];
      const entryRegex = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
      let match;

      while ((match = entryRegex.exec(xml)) !== null) {
        const text = match[3]
          .replace(/&amp;/g, "&")
          .replace(/&lt;/g, "<")
          .replace(/&gt;/g, ">")
          .replace(/&quot;/g, '"')
          .replace(/&#39;/g, "'")
          .replace(/<[^>]+>/g, "")
          .trim();

        if (text) {
          segments.push({
            start: parseFloat(match[1]),
            duration: parseFloat(match[2]),
            text,
          });
          textParts.push(text);
        }
      }

      if (segments.length > 0) {
        return {
          ok: true,
          text: textParts.join(" "),
          segments,
          language: selectedLang,
          autoGenerated,
        };
      }
    } catch {
      continue;
    }
  }

  return { ok: false, error: "자막을 찾을 수 없습니다. 자막이 없는 영상이거나 비공개 영상일 수 있습니다." };
}

async function fetchVideoInfo(videoId: string): Promise<{ title: string; author: string; thumbnail: string }> {
  try {
    const resp = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    );
    if (resp.ok) {
      const data = await resp.json();
      return {
        title: data.title || "",
        author: data.author_name || "",
        thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
      };
    }
  } catch { /* ignore */ }
  return { title: "", author: "", thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` };
}

export async function POST(request: Request) {
  try {
    const { videoId, mode = "summary" } = await request.json();

    if (!videoId || typeof videoId !== "string" || !/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
      return NextResponse.json({ error: "유효하지 않은 영상 ID입니다." }, { status: 400 });
    }

    const apiKey = await getSecret("ANTHROPIC_API_KEY");
    if (!apiKey) {
      return NextResponse.json({ error: "API 키가 설정되지 않았습니다." }, { status: 500 });
    }

    // Fetch video info and transcript in parallel
    const [videoInfo, transcriptResult] = await Promise.all([
      fetchVideoInfo(videoId),
      fetchTranscript(videoId),
    ]);

    if (!transcriptResult.ok) {
      return NextResponse.json({
        error: transcriptResult.error,
        videoInfo,
      }, { status: 422 });
    }

    const transcriptText = transcriptResult.text!;
    const maxChars = 300_000;
    const truncated = transcriptText.length > maxChars
      ? transcriptText.slice(0, maxChars) + "\n\n... (자막이 너무 길어 일부만 포함)"
      : transcriptText;

    const titleHint = videoInfo.title ? `\n영상 제목: ${videoInfo.title}` : "";

    const prompts: Record<string, string> = {
      summary: `다음은 YouTube 영상의 자막입니다.${titleHint}

이 영상의 내용을 한국어로 요약해주세요.

요약 형식:
1. **핵심 주제** (1-2줄)
2. **주요 내용** (핵심 포인트 3-7개, 불릿)
3. **결론/시사점** (1-2줄)

자막:
${truncated}`,

      full: `다음은 YouTube 영상의 자막입니다.${titleHint}

이 자막을 깔끔하게 정리해주세요:
- 말의 반복, 군더더기를 제거
- 주제별로 구분
- 읽기 쉽게 문단 나누기
- 한국어로 작성 (원문이 영어면 번역)

자막:
${truncated}`,

      key_points: `다음은 YouTube 영상의 자막입니다.${titleHint}

핵심 포인트만 추출해주세요:
- 가장 중요한 인사이트 5-10개
- 각 포인트는 1-2줄로 간결하게
- 실행 가능한 조언이 있다면 별도 표시

자막:
${truncated}`,
    };

    const client = new Anthropic({ apiKey });
    const response = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 4000,
      system: "당신은 영상 내용을 정확하고 깊이있게 요약하는 전문가입니다. 마크다운 포맷으로 작성하세요.",
      messages: [{ role: "user", content: prompts[mode] || prompts.summary }],
    });

    const summary = response.content[0].type === "text" ? response.content[0].text : "";

    return NextResponse.json({
      videoInfo,
      transcript: {
        text: transcriptText,
        language: transcriptResult.language,
        autoGenerated: transcriptResult.autoGenerated,
        charCount: transcriptText.length,
      },
      summary,
      mode,
    });
  } catch (error) {
    console.error("YouTube analyze error:", error);
    return NextResponse.json({ error: "분석 중 오류가 발생했습니다." }, { status: 500 });
  }
}
